-- Write your migrate up statements here

CREATE TABLE POLICIES (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    OWNER_ID UUID NOT NULL,
    RESOURCE TEXT NOT NULL,
    BUCKET_CAPACITY INTEGER NOT NULL,
    TIME_IN_SECONDS INTEGER NOT NULL,
    REFILL_RATE_PER_SECOND FLOAT NOT NULL GENERATED ALWAYS AS (bucket_capacity::FLOAT / time_in_seconds::FLOAT) STORED,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (OWNER_ID) REFERENCES OWNERS(id)
);

---- create above / drop below ----

DROP TABLE IF EXISTS POLICIES;
