# global:
#   scrape_interval: 5s

# scrape_configs:
#   - job_name: prometheus
#     static_configs: 
#       - targets: ["172.20.96.1:6003"]

scrape_configs:
  # Job 1: Internal Prometheus monitoring
  - job_name: "rl_server"
    scrape_interval: 5s     # Overrides global setting for this specific job
    static_configs:
      - targets: ["rate_limiter:6003"]
